[2025-03-14T11:46:21.849+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T11:46:21.860+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mtrix_clientes_edi.process_txt_to_postgres manual__2025-03-14T11:46:19.845161+00:00 [queued]>
[2025-03-14T11:46:21.866+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mtrix_clientes_edi.process_txt_to_postgres manual__2025-03-14T11:46:19.845161+00:00 [queued]>
[2025-03-14T11:46:21.867+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-14T11:46:21.876+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_txt_to_postgres> on 2025-03-14 11:46:19.845161+00:00
[2025-03-14T11:46:21.881+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T11:46:21.882+0000] {standard_task_runner.py:72} INFO - Started process 73 to run task
[2025-03-14T11:46:21.883+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mtrix_clientes_edi', 'process_txt_to_postgres', 'manual__2025-03-14T11:46:19.845161+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/mtrix_clientes_edi.py', '--cfg-path', '/tmp/tmp9fcvsw0f']
[2025-03-14T11:46:21.885+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask process_txt_to_postgres
[2025-03-14T11:46:22.035+0000] {task_command.py:467} INFO - Running <TaskInstance: mtrix_clientes_edi.process_txt_to_postgres manual__2025-03-14T11:46:19.845161+00:00 [running]> on host 6741e125235f
[2025-03-14T11:46:22.090+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='mtrix_clientes_edi' AIRFLOW_CTX_TASK_ID='process_txt_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T11:46:19.845161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T11:46:19.845161+00:00'
[2025-03-14T11:46:22.090+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T11:46:22.111+0000] {logging_mixin.py:190} INFO - Erro ao ler arquivo CLIENTESUN12032025140133.txt: [Errno 2] No such file or directory: 'CLIENTESUN12032025140133.txt'
[2025-03-14T11:46:22.111+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T11:46:22.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T11:46:22.120+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=mtrix_clientes_edi, task_id=process_txt_to_postgres, run_id=manual__2025-03-14T11:46:19.845161+00:00, execution_date=20250314T114619, start_date=20250314T114621, end_date=20250314T114622
[2025-03-14T11:46:22.176+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T11:46:22.189+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T11:46:22.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
