[2025-03-14T14:01:31.721+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T14:01:31.734+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:01:30.855032+00:00 [queued]>
[2025-03-14T14:01:31.741+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:01:30.855032+00:00 [queued]>
[2025-03-14T14:01:31.741+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-14T14:01:31.753+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_txt_to_postgres> on 2025-03-14 14:01:30.855032+00:00
[2025-03-14T14:01:31.761+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T14:01:31.762+0000] {standard_task_runner.py:72} INFO - Started process 73 to run task
[2025-03-14T14:01:31.762+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mtrix_vendas_edi', 'process_txt_to_postgres', 'manual__2025-03-14T14:01:30.855032+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/mtrix_vendas_edi.py', '--cfg-path', '/tmp/tmply5awptg']
[2025-03-14T14:01:31.764+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask process_txt_to_postgres
[2025-03-14T14:01:31.799+0000] {task_command.py:467} INFO - Running <TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:01:30.855032+00:00 [running]> on host 266a86bf832d
[2025-03-14T14:01:31.864+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='mtrix_vendas_edi' AIRFLOW_CTX_TASK_ID='process_txt_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T14:01:30.855032+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T14:01:30.855032+00:00'
[2025-03-14T14:01:31.865+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T14:01:31.892+0000] {logging_mixin.py:190} INFO - Processando arquivo: /opt/***/data/arquivos_mtrix/VENDASUN12032025140133.txt
[2025-03-14T14:01:31.908+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mtrix_vendas_edi.py", line 154, in process_txt_to_postgres
    cur.execute(INSERT_SQL, data_tuple)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "NaT"
LINE 16:     'H', 'VENDA113027842', '8000838', 'NaT'::timestamp, 'NaN...
                                               ^

[2025-03-14T14:01:31.920+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=mtrix_vendas_edi, task_id=process_txt_to_postgres, run_id=manual__2025-03-14T14:01:30.855032+00:00, execution_date=20250314T140130, start_date=20250314T140131, end_date=20250314T140131
[2025-03-14T14:01:31.942+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T14:01:31.943+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task process_txt_to_postgres (invalid input syntax for type timestamp: "NaT"
LINE 16:     'H', 'VENDA113027842', '8000838', 'NaT'::timestamp, 'NaN...
                                               ^
; 73)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mtrix_vendas_edi.py", line 154, in process_txt_to_postgres
    cur.execute(INSERT_SQL, data_tuple)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "NaT"
LINE 16:     'H', 'VENDA113027842', '8000838', 'NaT'::timestamp, 'NaN...
                                               ^

[2025-03-14T14:01:31.976+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-14T14:01:31.993+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T14:01:31.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
